import type { VehicleRecord } from "@attra/shared";

export const seedVehicles: VehicleRecord[] = [
  {
    id: "veh-porsche-911-carrera",
    externalStockId: "ATTRA-1001",
    brand: "Porsche",
    model: "911",
    version: "Carrera",
    title: "Porsche 911 Carrera",
    yearModel: 2024,
    price: 980000,
    mileageKm: 1200,
    fuelType: "Gasolina",
    transmission: "PDK",
    bodyType: "Coupé",
    armored: false,
    color: "Cinza",
    storeUnit: "São Paulo",
    available: true,
    vehicleUrl: "https://attra.example/veiculos/veh-porsche-911-carrera",
    mainImageUrl: "https://images.attra.example/911-carrera.jpg",
    imageUrls: ["https://images.attra.example/911-carrera.jpg"],
    usageProfile: "uso_diario",
    positioningProfile: "esportivo_premium"
  },
  {
    id: "veh-porsche-cayenne-hybrid",
    externalStockId: "ATTRA-1002",
    brand: "Porsche",
    model: "Cayenne",
    version: "E-Hybrid",
    title: "Porsche Cayenne E-Hybrid",
    yearModel: 2023,
    price: 890000,
    mileageKm: 8000,
    fuelType: "Híbrido",
    transmission: "Automática",
    bodyType: "SUV",
    armored: false,
    color: "Preto",
    storeUnit: "São Paulo",
    available: true,
    vehicleUrl: "https://attra.example/veiculos/veh-porsche-cayenne-hybrid",
    mainImageUrl: "https://images.attra.example/cayenne-hybrid.jpg",
    imageUrls: ["https://images.attra.example/cayenne-hybrid.jpg"],
    usageProfile: "familia_executiva",
    positioningProfile: "premium_equilibrado"
  },
  {
    id: "veh-bmw-x5-50e",
    externalStockId: "ATTRA-1003",
    brand: "BMW",
    model: "X5",
    version: "xDrive50e",
    title: "BMW X5 xDrive50e",
    yearModel: 2024,
    price: 760000,
    mileageKm: 3500,
    fuelType: "Híbrido",
    transmission: "Automática",
    bodyType: "SUV",
    armored: true,
    color: "Azul",
    storeUnit: "Campinas",
    available: true,
    vehicleUrl: "https://attra.example/veiculos/veh-bmw-x5-50e",
    mainImageUrl: "https://images.attra.example/bmw-x5-50e.jpg",
    imageUrls: ["https://images.attra.example/bmw-x5-50e.jpg"],
    usageProfile: "familia_executiva",
    positioningProfile: "premium_equilibrado"
  },
  {
    id: "veh-mercedes-c43",
    externalStockId: "ATTRA-1004",
    brand: "Mercedes-Benz",
    model: "C 43",
    version: "AMG 4MATIC",
    title: "Mercedes-AMG C 43 4MATIC",
    yearModel: 2023,
    price: 540000,
    mileageKm: 5200,
    fuelType: "Gasolina",
    transmission: "Automática",
    bodyType: "Sedan",
    armored: false,
    color: "Branco",
    storeUnit: "Ribeirão Preto",
    available: false,
    vehicleUrl: "https://attra.example/veiculos/veh-mercedes-c43",
    mainImageUrl: "https://images.attra.example/mercedes-c43.jpg",
    imageUrls: ["https://images.attra.example/mercedes-c43.jpg"],
    usageProfile: "executivo",
    positioningProfile: "esportivo_premium"
  }
];
